export const siteConfig = {
  title: "Sanjeed's Library, an interactive 3D bookshelf",
  applicationName: "Sanjeed's Library",
  description: 'Explore a personal reading library as one continuous, tactile 3D shelf.',
  wordmark: "SANJEED'S LIBRARY",
  collectionName: 'A READING LIFE IN 3D',
  editionEyebrow: 'PERSONAL LIBRARY',
  coverImprint: "SANJEED'S LIBRARY",
  coverTagline: 'BOOKS WORTH KEEPING CLOSE',
  spineMark: 'SL',
  bookLinkLabel: 'Open book details',
  socialImageAlt: 'A warm, tactile 3D bookshelf from Sanjeed’s personal library.',
  enableOptionalStripeArchive: false,
  independentNote: 'Drag, scroll, use arrow keys, or search the shelf.',
} as const;
