export const siteConfig = {
  title: "Sanjeed's Library, an interactive 3D bookshelf",
  applicationName: "Sanjeed's Library",
  description: 'Browse a personal reading library as a dense cover grid, with an optional 3D shelf.',
  wordmark: "SANJEED'S LIBRARY",
  collectionName: 'A READING LIFE',
  editionEyebrow: 'PERSONAL LIBRARY',
  coverImprint: "SANJEED'S LIBRARY",
  coverTagline: 'BOOKS WORTH KEEPING CLOSE',
  spineMark: 'SL',
  bookLinkLabel: 'Open book details',
  socialImageAlt: 'A warm, tactile 3D bookshelf from Sanjeed’s personal library.',
  enableOptionalStripeArchive: false,
  independentNote: 'Scroll the grid, filter by status, or switch to the 3D shelf.',
} as const;
